### ISSUE TITLE
Add logging to default handlers

### ISSUE THREAD

**Issue by dustinmoris** [dustinmoris/AspNetCore.Lambda#10]
Add logging for different log levels to help diagnose issues if they occur.

In ASP.NET Core middleware and other infrastructure code logs a lot of debug information when the log level is turned up. This is helpful when someone tries to diagnose low level issues such as routing for example.

ASP.NET Core Lambda should also log key events in the default HttpHandler functions when debug level is turned on.

**Comment by dustinmoris** [comment]
After playing around with logging for a while I decided to add a default logger to the `HttpHandlerContext` and to log if the `LambdaMiddleware` was able to handle the incoming HTTP request but nothing more than that.

Logging every small handler turned out to be an overkill and in some instances I needed to know which handlers passed and which failed and in other instances I needed to know both. Whatever I would set as default it would never match every use case that someone might need and since adding logging in between handlers can be very easy achieved with the existing framework I decided against very verbose logging in default handlers.

**Comment by Lanayx** [comment]
How do I get ILogger instance inside webApp? I want to do some custom logging in different places in the code that handles get/post requests.

**Comment by dustinmoris** [comment]
Hi @Lanayx, you can get a logger like this from inside a `HttpHandler`:

```fsharp
// Get the default logger:
        let defaultLogger = ctx.GetLogger()

        // Create a custom logger:
        let loggerFactory = ctx.GetService<ILoggerFactory>()
        let customLogger = loggerFactory.CreateLogger("<NameOfLogger>")
```

**Comment by Lanayx** [comment]
@dustinmoris 
Sorry, I don't see GetLogger method available:
![image](https://user-images.githubusercontent.com/3329606/28773781-9a40cbe8-75f3-11e7-89c5-301aeb39fab3.png)
![image](https://user-images.githubusercontent.com/3329606/28773813-b97fdce2-75f3-11e7-8a25-4711ff2a07fb.png)
Am I missing something?

**Comment by dustinmoris** [comment]
Oh yes, please open the Giraffe.HttpContextExtensions module.

**Comment by Lanayx** [comment]
Thanks a lot, this works =)
