### ISSUE TITLE
Development Environement

### ISSUE THREAD

**Issue by xdaDaveShaw** [dustinmoris/AspNetCore.Lambda#13]
Is it worth updating the README with some suggestions on Developing? Although I'm still new to dotnet core apps I'm struggling to find the best way to work on this code. 

Do people developer this in VS2015 / 17 or VS Code?

I'd assume VS Code given the lack of a SLN file. If it is, can the `.vscode\tasks.json` file be added?

Or is it all just command line?

**Comment by dustinmoris** [comment]
Hi Dave,

That is a good idea. At the moment there is no ideal developing environment for F# on .NET Core, as VS 2015 doesn't support it at all, VS 2017 hasn't got the tooling for F# and .NET Core yet AFAIK and VS Code + Ionide works, but doesn't work great.

There is currently #9 in progress and when it is done I think we can update the README with instructions for a working setup.

**Comment by dustinmoris** [comment]
Hi, so I finished the migration to RC4 and have updated the [README here](https://github.com/dustinmoris/AspNetCore.Lambda#building-and-developing).
