### ISSUE TITLE
Remove dependency on Microsoft.AspNetCore.Hosting

### ISSUE THREAD

**Issue by davidfowl** [dustinmoris/AspNetCore.Lambda#22]
You probably only need Microsoft.AspNetCore.Hosting.Abstractions https://github.com/dustinmoris/AspNetCore.Lambda/blob/47aedc846166d5564fbb8d17388e59f0c094757d/src/AspNetCore.Lambda/AspNetCore.Lambda.fsproj#L32

**Comment by dustinmoris** [comment]
Thank you, just pushed the change to the dev branch. Thanks for checking my code :)
